import { getData, postData, postDataList } from "lib/request";

export const listDebit = async (params: any) => await getData("Debit", params);
export const listDebitMuaBan = async (params: any) => await getData("Debit/muaban", params);
export const listDebitDauKyKH = async (params: any) => await getData("Debit/daukykh", params);
export const listDebitDauKyNCC = async (params: any) => await getData("Debit/daukyncc", params);
export const listDebitDispatch = async (params: any) => await getData("Debit/dispatch", params);
export const listDebitCuocTamThu = async (params: any) => await getData("Debit/cuoctamthu", params);
export const listDebitService = async (params: any) => await getData("Debit/service", params);
export const showDebit = async (params: any) => await getData("Debit/show", params);
export const showDebitByFileId = async (params: any) => await getData("Debit/show/byFileId", params);
export const deleteDebit = async (params: any) => await postData("Debit/delete", params);
export const deleteMultiDebit = async (params: any) => await postData("Debit/delete/multi", params);
export const addDebit = async (params: any) => await postData("Debit/create", params);
export const addDebitDauKyKH = async (params: any) => await postData("Debit/create/daukykh", params);
export const addDebitDauKyNCC = async (params: any) => await postData("Debit/create/daukyncc", params);
export const addDebitMuaBan= async (params: any) => await postData("Debit/create/muaban", params);
export const updateDebitDauKyVaMuaBan = async (params: any) => await postData("Debit/update/daukyvamuaban", params);
export const addDebitService = async (params: any) => await postData("Debit/service/create", params);
export const addDebitNangha = async (params: any) => await postData("Debit/nangha/create", params);
export const updateDebitFileGia = async (params: any) => await postData("Debit/updateFileGia", params);
export const confirmFileGia = async (params: any) => await postData("Debit/confirmFileGia", params);
export const updateStatusDebit = async (params: any) => await postData("Debit/update/status", params);
export const confirmChiPhiHaiQuan = async (params: any) => await postData("Debit/confirmChiPhiHaiQuan", params);